### ISSUE TITLE
Contacting the author

### ISSUE THREAD

**Issue by d-bergman** [turanar/stellaris-tech-tree#7]
Been looking to contact the author of the stellaris tech tree. I have some coding questions for them based on some modified code i have. Pls contact me at revaleth.malthormiel@gmail.com

**Comment by eva-cosma** [comment]
From my best guess you are probably worried about the copyright, because otherwise I do not really understand the need of communications over email.

Either way the license is MIT and I am not the original author,  but a bit more detail would be appreciated. If it truly is something that needs to be kept to an email conversation then perhaps turanar will be able to contact you, or not, this repo is inactive.

**Comment by d-bergman** [comment]
Nah. It’s not about copyright. 
I cloned the entire repository and did some heavy modifying. Trying to use the same idea and template. Some images. For a game I am developing. 

Some of the code I don’t know really what exactly is going on. I got 90% working in my modified code, however it’s the tooltipster stuff that has me puzzled. I have been trying to add new children to my main starter tech but when I do add. The tooltip doesn’t open when clicked. Only opens on the second one. My wife and I have been trying to figure it out for ages. 

This is why I am wanting to contact the author because ofc they know what is actually happening in the code. 

THis is the modified look. https://d-bergman.github.io/geministation/modtree.html

**Comment by eva-cosma** [comment]
I will fork it later today to see what I can do to help. I don't remember the code for tooltiper but I know it is a pain, it likes to break everytime.

**Comment by d-bergman** [comment]
Okay great!
Yeah I’ve been struggling with that tooltipster thing for awhile. 
I decided to finish setting up one main before adding children. 

When the second child was added. The main starter tech’s tool tip wouldn’t open on click. The child’s tooltip would open. 

Then if I add a third, the third one would open. But the two behind it wouldn’t open. And it keeps going. Only the last one opens. 

That’s pretty much the only thing I can’t figure out in the code.

**Comment by d-bergman** [comment]
I did alot of debugging. And it turns out that the tooltip works for only 1 element per tree. It doesn't show the "extra-data" div content for all elements but only for 1 element per tree.

**Comment by eva-cosma** [comment]
No more luck on my side, not sure how it works/how it doesn't. Ill think about why, but for now I can't give you an answer, sorry!

**Comment by Tsudico** [comment]
I've got a modified version of this tech tree that I plan on putting pull requests in for soon. I might be able to help if you are having issues because I've had to look through a lot of the code to get my modifications to work.

The modifications can be seen here:
https://tsudico.github.io/stellaris-tech-tree/vanilla/index.html
